# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\"\'\n\x0fTextFileRequest\x12\x14\n\x0cjson_content\x18\x01 \x01(\t\"\"\n\x11\x41udioFileResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32V\n\x13TextToSpeechService\x12?\n\x17\x43onvertTextFileToSpeech\x12\x10.TextFileRequest\x1a\x12.AudioFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTFILEREQUEST']._serialized_start=13
  _globals['_TEXTFILEREQUEST']._serialized_end=52
  _globals['_AUDIOFILERESPONSE']._serialized_start=54
  _globals['_AUDIOFILERESPONSE']._serialized_end=88
  _globals['_TEXTTOSPEECHSERVICE']._serialized_start=90
  _globals['_TEXTTOSPEECHSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
